---
apiVersion: v1
kind: Service
metadata:
  name: ramped-service
  namespace: update-strategies
  labels:
    app: ramped-demo
    strategy: ramped
spec:
  type: ClusterIP
  selector:
    app: ramped-demo
  ports:
    - name: http
      port: 80
      targetPort: http
