---
apiVersion: v1
kind: Service
metadata:
  name: blue-green-preview
  namespace: update-strategies
  labels:
    app: blue-green-demo
    strategy: blue-green
    track: preview
spec:
  type: ClusterIP
  selector:
    app: blue-green-demo
    version: green
  ports:
    - name: http
      port: 80
      targetPort: http
