---
apiVersion: v1
kind: Service
metadata:
  name: canary-service
  namespace: update-strategies
  labels:
    app: canary-demo
    strategy: canary
spec:
  type: ClusterIP
  selector:
    app: canary-demo
  ports:
    - name: http
      port: 80
      targetPort: http
